import React ,{Component} from 'react';
import { Text, View, ScrollView } from 'react-native';
 
import {_alert} from "../../utils"
import SimpleComp from "../../../comps/SimpleComp"
// import PureComp from "../../../comps/PureComp"
/* 
不能使用

function PureComp(){
  return <Text> i'm PureComps</Text> 
} */

export default class Page extends Component {

  constructor(props) {
    super(props)
    
  }
  config = {
    navigationBarTitleText: '样式',
  
  }

  feedCallExpression_isReferencedIdentifier  () {
    /* 对于  一下格式的代码会做处理
      必须是on开头。。。，而且是this.props来的
      var onXXX=this.props.acb;
      onXXX()
=>
    this.props.acb()
    */
    var { onClick, pStr }= this.props;
    onClick(pStr)

  }


  feedCallExpression_isReferencedMemberExpression (){
      /* 对于  一下格式的代码会做处理
      var onXXX=this.props.acb;
      onXXX.hhh()
=>
    this.props.acb.hhh()
    */
    var { onClick }= this.props;
    onClick.call()
    //以下不会处理不是on开头

    var { notonClick }= this.props;
    notonClick()
    //以下不会处理不是this.props来的

    var { onXXX }= this.method;
    onXXX.call()
  }

  method(str){
    this.props.onClick(str)
  }

  onPress(){
    _alert("onPress")
  }

  getUI= () =>{
    // 无法返回内容 这个方法是事件形式触发的
    // return <Text>i'm compProp component</Text>

  }
/* 

// 不支持
  aUIGeneate = () =>{
    return <Text> i'm generated by aUIGeneate </Text>
  } */

  render() {
 
     return (
       <View style={{flex:1,justifyContent:'center', alignItems:"center",display: "flex", flexDirection: "column" }}>
          {/* {PureComp()}   */}
          {/* {this.aUIGeneate()} */}
          <SimpleComp
            name="SimpleComp"
            renderPropComp = {<Text>i'm  component passed from Parent</Text>}
            onGetUI = {this.getUI}
            onClick = {this.onPress}
            click2 = {this.onPress}
          >
            <Text>i'm children component</Text>
          </SimpleComp>
      </View>
     );
  }
}

// const styles = StyleSheet.create({
//   txt:{
//     color:"red"
//   }
// });
